version: 2.1

workflows:
  build:
    jobs:
      - build-ros-componenet

jobs:
  build-ros-componenet:
    docker:
      - image: ros:iron-ros-base-jammy
    working_directory: /ws/src
    steps:
      - run:
          name: "create workspace"
          command: "mkdir -p /ws/src"
      - run:
          name: "checkout via https"
          working_directory: "/ws/src"
          command: "git clone https://github.com/cellumation/snapshotter.git -b $CIRCLE_BRANCH"
      - run:
          name: "build snapshotter"
          working_directory: /ws/src/snapshotter
          command: |
            source /opt/ros/iron/setup.bash
            colcon build
            colcon test
