string filename   # Name of bag file to save snapshot to. Needs to be a full path ending in .bag
---

bool success    # True if snapshot succesfully written to disk
string message  # Error description if failed
builtin_interfaces/Time first_timestamp   # First timestamp in the bag (excluding latched topics)
builtin_interfaces/Time last_timestamp    # Last timestamp in the bag
